# Generated by Django 2.1.2 on 2018-10-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auction_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6),
        ),
    ]
