# Generated by Django 2.1.5 on 2019-01-24 11:36

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20181030_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='author',
            field=models.CharField(max_length=128, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bidder',
            field=models.CharField(blank=True, max_length=128, verbose_name=django.contrib.auth.models.User),
        ),
    ]
