# Generated by Django 2.1.2 on 2019-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20190124_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Banned', 'Banned'), ('Due', 'Due'), ('Adjudicated', 'Adjudicated')], default='Active', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='author',
            field=models.CharField(max_length=128),
        ),
    ]
