# Generated by Django 2.1.5 on 2019-03-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20190305_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default='testi', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default='testo', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(default='testiname', max_length=128),
            preserve_default=False,
        ),
    ]
