# Generated by Django 2.1.5 on 2019-03-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_auto_20190305_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='username',
        ),
    ]
